version: '3'

services:
  db:
    image: postgres
    environment:
            POSTGRES_PASSWORD: postgres_password

  web:
    build: .
    volumes:
      - .:/~/code/Rosevandergiessen/first-django/airline
    ports:
      - "8000:8000"
